baseURL: https://cschioelerhansen.netlify.app/
author: Christian Schiøler Hansen
copyright: Copyright © 2023, Christian Schiøler Hansen; all rights reserved.
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
ignoreErrors: error-remote-getjson
theme: hugo-paper
title: Christian Schiøler Hansen
params:
  avatar: christianschioeler@gmail.com
  bio: Explore my content
  color: linen
  github: CSchioeler
  twitch: suspicioussamaritan
  name: Christian
  twitter: CSchiolerHansen
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 10
taxonomies:
  category: categories
  series: series
  tag: tags
privacy:
  instagram:
    disabled: no
    simple: yes
  twitter:
    disabled: no
    enableDNT: yes
    simple: yes
  vimeo:
    disabled: no
    simple: yes
  youtube:
    disabled: no
    privacyEnhanced: yes
services:
  instagram:
    disableInlineCSS: yes
  twitter:
    disableInlineCSS: yes
